# Generated by Django 4.1.2 on 2023-03-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_utilisateur', models.CharField(default='', max_length=50)),
                ('nom_utilisateur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('nom', models.CharField(max_length=30)),
                ('motdepasse', models.CharField(max_length=30)),
            ],
        ),
    ]
