# Generated by Django 4.1.2 on 2023-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_GES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='id_doc',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='historique',
            name='id_document',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
